openapi: 3.0.0
info:
  title: Currency Converter API
  version: "1.0.0"
  description: API for converting currencies and fetching exchange rates using the Currency Beacon API.
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /exchange-rate:
    get:
      summary: Get current exchange rate
      description: Fetch the current exchange rate between two currencies.
      parameters:
        - name: from
          in: query
          required: true
          description: The base currency (e.g., USD).
          schema:
            type: string
        - name: to
          in: query
          required: true
          description: The target currency (e.g., BRL).
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateResponse'
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /historical-rates:
    get:
      summary: Get historical exchange rates
      description: Fetch historical exchange rates for a given time range.
      parameters:
        - name: from
          in: query
          required: true
          description: The base currency (e.g., USD).
          schema:
            type: string
        - name: to
          in: query
          required: true
          description: The target currency (e.g., BRL).
          schema:
            type: string
        - name: days
          in: query
          required: true
          description: Number of days for historical data.
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoricalRatesResponse'
        "400":
          description: Bad request
        "500":
          description: Internal server error
components:
  schemas:
    ExchangeRateResponse:
      type: object
      properties:
        from:
          type: string
          description: The base currency.
        to:
          type: string
          description: The target currency.
        rate:
          type: number
          description: The current exchange rate.
        timestamp:
          type: string
          format: date-time
          description: The timestamp of the exchange rate.
    HistoricalRatesResponse:
      type: object
      properties:
        from:
          type: string
          description: The base currency.
        to:
          type: string
          description: The target currency.
        rates:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
                description: The date of the rate.
              rate:
                type: number
                description: The exchange rate on that date.
        averageRate:
          type: number
          description: The average exchange rate over the specified period.
        highestRate:
          type: number
          description: The highest exchange rate during the specified period.
        lowestRate:
          type: number
          description: The lowest exchange rate during the specified period.